import { type Signer, type SignerJsonRpcConfirmation } from "@ckb-ccc/core";
import { CameraView, useCameraPermissions } from "expo-camera";
import * as Clipboard from "expo-clipboard";
import { useCallback, useEffect, useRef, useState } from "react";
import { BackHandler, LayoutChangeEvent, Linking, Pressable, StyleSheet, useWindowDimensions, View } from "react-native";
import { ActivityIndicator, Button as PaperButton, Card as PaperCard, Chip, Dialog, Divider, Icon, Portal, Text, TextInput as PaperTextInput, useTheme } from "react-native-paper";
import { KeyboardAwareScrollView, type KeyboardAwareScrollViewRef } from "react-native-keyboard-controller";

import { InfoCard } from "../components/InfoCard";
import { KhieIcon } from "../components/KhieIcon";
import { useI18n, type Translate } from "../i18n";
import { type ApprovalItem } from "../khie/approvalQueue";
import { type KhieProviderSessionState } from "../khie/KhieProviderSession";
import { TransactionApprovalDetails } from "../khie/TransactionApprovalDetails";
import type { Network } from "../wallet/types";
import { FloatingLabelTextInput, formatKhieError, QuietQrCode } from "./components";
import { styles } from "./styles";

export function KhieScreen({ state, pairing, approval, network, signer, onScan, onPair, onCancelPairing, onConnectRelay, onUnpair, onRespond }: { state: KhieProviderSessionState; pairing: boolean; approval?: ApprovalItem; network: Network; signer?: Signer; onScan: () => void; onPair: (endpoint: string) => Promise<boolean>; onCancelPairing: () => void; onConnectRelay: (address: string) => Promise<boolean>; onUnpair: () => Promise<void>; onRespond: (approved: boolean) => void }) {
  const { t } = useI18n(); const theme = useTheme(); const { width } = useWindowDimensions(); const scrollRef = useRef<KeyboardAwareScrollViewRef>(null); const [endpoint, setEndpoint] = useState(""); const [endpointCopied, setEndpointCopied] = useState(false); const endpointCopyTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined); const approvalScrolledId = useRef<number | undefined>(undefined); const khieContentOffsetY = useRef(0); const [relayAddress, setRelayAddress] = useState(state.relayAddress); const [advancedSettingsOpen, setAdvancedSettingsOpen] = useState(false); const qrSize = Math.max(180, Math.min(420, width - 64));
  useEffect(() => setRelayAddress(state.relayAddress), [state.relayAddress]); useEffect(() => { if (!approval) approvalScrolledId.current = undefined; }, [approval]);
  const scrollToApproval = useCallback((event: LayoutChangeEvent) => { if (!approval || approvalScrolledId.current === approval.id) return; approvalScrolledId.current = approval.id; const { y } = event.nativeEvent.layout; requestAnimationFrame(() => scrollRef.current?.scrollTo({ y: khieContentOffsetY.current + y, animated: true })); }, [approval]);
  useEffect(() => { setEndpointCopied(false); if (endpointCopyTimer.current) clearTimeout(endpointCopyTimer.current); }, [state.endpoint]); useEffect(() => () => { if (endpointCopyTimer.current) clearTimeout(endpointCopyTimer.current); }, []);
  const copyEndpoint = async () => { if (!state.endpoint) return; await Clipboard.setStringAsync(state.endpoint); setEndpointCopied(true); if (endpointCopyTimer.current) clearTimeout(endpointCopyTimer.current); endpointCopyTimer.current = setTimeout(() => setEndpointCopied(false), 1600); };
  const pair = async () => { if (await onPair(endpoint)) setEndpoint(""); };
  const connectionPath = !state.remotePeer?.active ? t("inactive") : state.remotePeer.direct ? t("direct") : t("relayed");
  return <KeyboardAwareScrollView ref={scrollRef} bottomOffset={16} contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled">
    <Text variant="headlineMedium">Khie</Text>
    <InfoCard title={t("khieIntroductionTitle")} description={t("khieIntroduction")} supportingText={t("khieNameMeaning")} icon={({ color, size }) => <KhieIcon size={size} color={color} />} />
    {pairing ? <View style={styles.pairingProgress}><ActivityIndicator size="large" /><Text variant="titleLarge">{t("pairingWithKhie")}</Text><PaperButton mode="text" onPress={onCancelPairing}>{t("cancel")}</PaperButton></View> : state.paired ? <View style={styles.khieContent} onLayout={(event) => { khieContentOffsetY.current = event.nativeEvent.layout.y; }}>
      <View style={styles.peerOverview}>{state.remotePeer ? <><Chip compact>{connectionPath}</Chip><View style={styles.flex}><Text variant="titleMedium" numberOfLines={1}>{state.remotePeer.name ?? t("unknown")}</Text><Text variant="bodySmall" numberOfLines={1}>{state.remotePeer.agentVersion ?? t("unknownAgent")}</Text></View></> : <Text variant="bodyMedium" style={styles.flex}>{t("loadingRemotePeerDetails")}</Text>}<PaperButton compact textColor={theme.colors.error} onPress={() => void onUnpair()}>{t("unpair")}</PaperButton></View>
      {state.remotePeer ? <View style={styles.peerMetadata}><View style={styles.metadataBlock}><Text variant="labelMedium">Peer ID</Text><Text variant="bodySmall" selectable numberOfLines={2} style={styles.mono}>{state.remotePeer.id}</Text></View><View style={styles.metadataBlock}><Text variant="labelMedium">{t("lastSeen")}</Text><Text variant="bodySmall" style={styles.mono}>{state.remotePeer.active ? t("active") : state.remotePeer.lastSeenAt === undefined ? t("notAvailable") : <InactiveLastSeen timestamp={state.remotePeer.lastSeenAt} />}</Text></View></View> : null}
      <Divider /><ApprovalPanel item={approval} network={network} signer={signer} onRespond={onRespond} onLayout={scrollToApproval} />
    </View> : <View style={styles.khieContent}>
      <View style={styles.khieMethod}><Text variant="titleSmall">{t("scanConnectorCode")}</Text><PaperButton mode="contained" icon="qrcode-scan" onPress={onScan}>{t("scanConnectorCode")}</PaperButton><FloatingLabelTextInput label={t("khieEndpoint")} placeholder={t("pastePairingCode")} autoCapitalize="none" autoCorrect={false} value={endpoint} onChangeText={setEndpoint} right={<PaperTextInput.Icon icon="arrow-right" disabled={!endpoint.trim()} onPress={() => void pair()} />} /></View>
      {state.error ? <View style={[styles.khieErrorNotice, { backgroundColor: theme.colors.surfaceVariant }]}><Icon source="information-outline" color={theme.colors.onSurfaceVariant} size={24} /><View style={[styles.flex, styles.khieErrorCopy]}><Text variant="labelLarge" style={{ color: theme.colors.onSurfaceVariant }}>{state.error.kind === "incompatible-pairing-code" ? t("incompatiblePairingCode") : t("operationFailed")}</Text><Text variant="bodyMedium" style={{ color: theme.colors.onSurfaceVariant }}>{formatKhieError(state.error, t)}</Text></View></View> : null}
      <View style={styles.orDivider}><Divider style={styles.flex} /><Text variant="labelMedium">{t("or")}</Text><Divider style={styles.flex} /></View>
      <View style={styles.khieMethod}><Text variant="titleSmall">{t("letConnectorScanThis")}</Text>{state.endpoint ? <><QuietQrCode value={state.endpoint} size={qrSize} /><Pressable accessibilityRole="button" accessibilityLabel={endpointCopied ? t("khieEndpointCopied") : t("copyKhieEndpoint")} accessibilityLiveRegion="polite" onPress={() => void copyEndpoint()} style={({ pressed }) => [styles.endpointCopyRow, pressed && styles.endpointCopyRowPressed]}><Text variant="labelSmall" numberOfLines={1} ellipsizeMode="tail" style={[styles.mono, styles.endpointCopyText]}>{state.endpoint}</Text><Icon source={endpointCopied ? "check" : "content-copy"} size={18} color={theme.colors.onSurfaceVariant} /></Pressable></> : <View style={[styles.qrPlaceholder, { height: qrSize + 24 }]}><ActivityIndicator /><Text variant="bodyMedium">{state.relayConnected ? t("preparingPairingCode") : t("connectingToRelay")}</Text>{state.ready && !state.relayConnected ? <PaperButton icon="refresh" loading={state.relayConnecting} disabled={state.relayConnecting} onPress={() => void onConnectRelay(state.relayAddress)}>{t("retryRelay")}</PaperButton> : null}</View>}</View>
      <PaperButton compact mode="text" icon={advancedSettingsOpen ? "chevron-up" : "chevron-down"} onPress={() => setAdvancedSettingsOpen((open) => !open)} style={styles.advancedSettingsToggle}>{t("advancedSettings")}</PaperButton>{advancedSettingsOpen ? <View style={styles.relaySettings}><FloatingLabelTextInput label={t("relayMultiaddr")} autoCapitalize="none" autoCorrect={false} value={relayAddress} onChangeText={setRelayAddress} returnKeyType="go" onSubmitEditing={() => void onConnectRelay(relayAddress)} /><PaperButton mode="contained-tonal" icon="connection" loading={state.relayConnecting} disabled={state.relayConnecting || !state.ready || !relayAddress.trim()} onPress={() => void onConnectRelay(relayAddress)}>{state.relayConnecting ? t("connecting") : state.relayConnected ? t("reconnect") : t("connectRelay")}</PaperButton></View> : null}
    </View>}
  </KeyboardAwareScrollView>;
}

export function ScannerScreen({ onCancel, onScanned }: { onCancel: () => void; onScanned: (value: string) => void }) {
  const { t } = useI18n(); const [permission, requestPermission] = useCameraPermissions(); const scanned = useRef(false);
  useEffect(() => { const subscription = BackHandler.addEventListener("hardwareBackPress", () => { onCancel(); return true; }); return () => subscription.remove(); }, [onCancel]);
  if (!permission) return <View style={[styles.page, styles.center]}><ActivityIndicator /></View>;
  if (!permission.granted) return <View style={styles.page}><Portal><Dialog visible onDismiss={onCancel}><Dialog.Icon icon="camera" /><Dialog.Title style={styles.centerText}>{t("cameraPermissionRequired")}</Dialog.Title><Dialog.Content><Text variant="bodyMedium">{t("cameraPermissionReason")}</Text></Dialog.Content><Dialog.Actions style={styles.dialogActions}><PaperButton contentStyle={styles.extraHorizontalButtonPadding} onPress={onCancel}>{t("back")}</PaperButton><PaperButton mode="contained" contentStyle={styles.extraHorizontalButtonPadding} onPress={() => { if (permission.canAskAgain) void requestPermission(); else void Linking.openSettings(); }}>{permission.canAskAgain ? t("allowCamera") : t("openSettings")}</PaperButton></Dialog.Actions></Dialog></Portal></View>;
  return <View style={styles.scanner}><CameraView style={StyleSheet.absoluteFill} barcodeScannerSettings={{ barcodeTypes: ["qr"] }} onBarcodeScanned={({ data }) => { if (!scanned.current) { scanned.current = true; onScanned(data); } }} /><View style={styles.scanFooter}><Text variant="titleMedium" style={styles.scanText}>{t("scanConnectorCode")}</Text><PaperButton mode="contained-tonal" icon="close" onPress={onCancel}>{t("cancelScan")}</PaperButton></View></View>;
}

function ApprovalPanel({ item, network, signer, onRespond, onLayout }: { item?: ApprovalItem; network: Network; signer?: Signer; onRespond: (approved: boolean) => void; onLayout?: (event: LayoutChangeEvent) => void }) {
  const { t } = useI18n(); const theme = useTheme();
  if (!item) return <Text variant="bodySmall" style={styles.requestIdle}>{t("readyForRequests")}</Text>;
  return <View onLayout={onLayout} style={styles.approvalPanel}><View style={styles.approvalHeading}><Icon source={approvalIcon(item.request)} size={24} color={theme.colors.primary} /><Text variant="titleLarge" style={styles.flex}>{approvalTitle(item.request, t)}</Text></View><View style={styles.metadataBlock}><Text variant="labelMedium">{t("network")}</Text><Text variant="bodyLarge">{approvalNetwork(item.request, network, t)}</Text></View><ApprovalDetails request={item.request} signer={signer} /><View style={styles.approvalActions}><PaperButton mode="outlined" contentStyle={styles.extraHorizontalButtonPadding} textColor={theme.colors.error} style={styles.flexAction} onPress={() => onRespond(false)}>{t("deny")}</PaperButton><PaperButton mode="contained" contentStyle={styles.extraHorizontalButtonPadding} style={styles.flexAction} onPress={() => onRespond(true)}>{t("allow")}</PaperButton></View></View>;
}

function ApprovalDetails({ request, signer }: { request: SignerJsonRpcConfirmation; signer?: Signer }) { const { t } = useI18n(); if (request.method === "connect") return <Text variant="bodyMedium">{t("connectApprovalDescription")}</Text>; if (request.method === "sign_message") return <PaperCard mode="contained"><PaperCard.Title title={t("message")} /><PaperCard.Content><Text variant="bodyMedium" selectable style={styles.mono}>{request.message.value}</Text></PaperCard.Content></PaperCard>; return signer ? <TransactionApprovalDetails client={signer.client} transaction={request.transaction} /> : <Text variant="bodyMedium">{t("unableToParse")}</Text>; }
function approvalIcon(request: SignerJsonRpcConfirmation) { return request.method === "connect" ? "link-variant" : request.method === "sign_message" ? "message-text-lock" : "file-sign"; }
export function approvalTitle(request: SignerJsonRpcConfirmation, t: Translate) { return request.method === "connect" ? t("webRequestsConnection") : request.method === "sign_message" ? t("confirmMessageSignature") : t("confirmTransactionSignature"); }
export function approvalNetwork(request: SignerJsonRpcConfirmation, fallback: Network, t: Translate) { if (request.method === "connect") return request.networkId === "ckb-mainnet" ? t("ckbMainnet") : request.networkId === "ckb-testnet" ? t("ckbTestnet") : request.networkId; return fallback === "mainnet" ? t("ckbMainnet") : t("ckbTestnet"); }
function InactiveLastSeen({ timestamp }: { timestamp: number }) { const { t } = useI18n(); const [now, setNow] = useState(Date.now); useEffect(() => { const timeout = setTimeout(() => setNow(Date.now()), nextElapsedDurationBoundary(timestamp, now)); return () => clearTimeout(timeout); }, [now, timestamp]); return formatElapsedDuration(timestamp, now, t); }
function formatElapsedDuration(timestamp: number, now: number, t: Translate) { const seconds = Math.max(0, Math.floor((now - timestamp) / 1_000)); if (seconds < 60) return seconds === 0 ? t("justNow") : t(seconds === 1 ? "secondAgo" : "secondsAgo", { count: seconds }); const minutes = Math.floor(seconds / 60); if (minutes < 60) return t(minutes === 1 ? "minuteAgo" : "minutesAgo", { count: minutes }); const hours = Math.floor(minutes / 60); if (hours < 24) return t(hours === 1 ? "hourAgo" : "hoursAgo", { count: hours }); const days = Math.floor(hours / 24); return t(days === 1 ? "dayAgo" : "daysAgo", { count: days }); }
function nextElapsedDurationBoundary(timestamp: number, now: number) { const elapsed = Math.max(0, now - timestamp); const minute = 60_000; const hour = 60 * minute; const day = 24 * hour; const unit = elapsed < minute ? 1_000 : elapsed < hour ? minute : elapsed < day ? hour : day; const nextBoundary = timestamp + (Math.floor(elapsed / unit) + 1) * unit; return Math.max(1, nextBoundary - now); }
