import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1 },
  body: { flex: 1 },
  page: { padding: 20, gap: 16 },
  onboardingStart: { flex: 1, alignItems: "center", padding: 20, paddingBottom: 12 },
  onboardingContent: { flex: 1, width: "100%", maxWidth: 420, justifyContent: "center", alignItems: "center", gap: 16 },
  onboardingSafetyNotice: { alignSelf: "stretch" },
  onboardingSafetyNoticeContent: { flexDirection: "row", alignItems: "flex-start", gap: 12, padding: 16 },
  onboardingSafetyNoticeCopy: { flex: 1, minWidth: 0, gap: 4 },
  settingsPage: { gap: 20 },
  center: { justifyContent: "center", alignItems: "center", gap: 16 },
  centerText: { textAlign: "center" },
  linkButtonLabel: { textDecorationLine: "underline" },
  trustBanner: { width: "100%", aspectRatio: 16 / 9, borderRadius: 24, overflow: "hidden" },
  trustBannerImage: { borderRadius: 24 },
  trustBannerTint: { position: "absolute", top: 0, right: 0, bottom: 0, left: 0 },
  trustRiskNotice: { gap: 12, padding: 16, borderRadius: 12 },
  trustRiskNoticeHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  trustRiskLink: { alignSelf: "flex-start" },
  balanceBlock: { alignItems: "center", gap: 4, paddingVertical: 24 },
  balanceValue: { width: "100%", alignItems: "center" },
  balanceIntegerRow: { width: "100%", flexDirection: "row", alignItems: "center" },
  balanceActionSpacer: { width: 48 },
  balanceNumber: { flex: 1, minWidth: 0, flexDirection: "row", flexWrap: "wrap", justifyContent: "center", alignItems: "baseline" },
  balanceInteger: { textAlign: "center", fontVariant: ["tabular-nums"] },
  balanceRefresh: { width: 48, margin: 0 },
  balanceFraction: { textAlign: "center", fontVariant: ["tabular-nums"] },
  amountRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  amountInput: { flex: 1 },
  recipientAddressInput: { height: 112, textAlignVertical: "top" },
  addressCopyRow: { width: "100%", minHeight: 40, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 8 },
  addressCopyRowCentered: { justifyContent: "center" },
  addressCopyText: { flex: 1, minWidth: 0 },
  cardContent: { gap: 12 },
  recommendedSection: { gap: 8 },
  recommendedApps: { gap: 8 },
  keyboardDialogLayer: { flex: 1 },
  keyboardDialog: { marginVertical: 24, maxHeight: "90%" },
  keyboardDialogContent: { flexShrink: 1, minHeight: 0 },
  dialogActions: { flexWrap: "wrap", rowGap: 8, columnGap: 8, justifyContent: "flex-end", paddingHorizontal: 24 },
  trustPicker: { gap: 16 },
  trustPickerActions: { alignItems: "flex-end" },
  trustDeviceResult: { gap: 4 },
  trustDeviceConnectCompact: { marginHorizontal: 16 },
  inlineProgress: { flexDirection: "row", alignItems: "center", gap: 12 },
  cardActions: { flexWrap: "wrap", rowGap: 8, paddingHorizontal: 16, paddingTop: 20, paddingBottom: 16 },
  walletListContent: { paddingHorizontal: 0 },
  walletListItem: { paddingRight: 16 },
  walletDeleteButton: { marginRight: 0, marginVertical: 0 },
  walletMenu: { alignSelf: "center" },
  extraHorizontalButtonPadding: { paddingHorizontal: 8 },
  metadataBlock: { gap: 4 },
  appInformationLink: { paddingHorizontal: 0 },
  appInformationSwitch: { paddingHorizontal: 0 },
  cardTitleLeft: { alignItems: "center", justifyContent: "center" },
  listItemCenteredAccessory: { alignSelf: "center", justifyContent: "center" },
  appInformationRow: { flexDirection: "row", alignItems: "flex-start", gap: 16 },
  appInformationLabel: { width: 112 },
  appInformationValue: { flex: 1, minWidth: 0, textAlign: "right" },
  updateStatus: { flexDirection: "row", alignItems: "center", gap: 8 },
  updateStatusText: { flex: 1, minWidth: 0 },
  mono: { fontFamily: "monospace" },
  mnemonicInput: { minHeight: 144, textAlignVertical: "top" },
  words: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  backButton: { alignSelf: "flex-start", marginLeft: -12 },
  networkSwitch: { width: "100%" },
  pairingProgress: { minHeight: 320, alignItems: "center", justifyContent: "center", gap: 16 },
  khieContent: { gap: 16 },
  peerOverview: { flexDirection: "row", alignItems: "center", gap: 8 },
  peerMetadata: { gap: 12 },
  khieMethod: { gap: 12 },
  endpointCopyRow: { width: "100%", minHeight: 40, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 8 },
  endpointCopyRowPressed: { opacity: 0.6 },
  endpointCopyText: { flex: 1, minWidth: 0 },
  khieErrorNotice: { flexDirection: "row", alignItems: "flex-start", gap: 16, paddingHorizontal: 16, paddingVertical: 14, borderRadius: 12 },
  khieErrorCopy: { gap: 2 },
  khieInput: { height: 56 },
  floatingInputContainer: { position: "relative" },
  floatingInputLabel: { position: "absolute", top: -8, left: 12, zIndex: 1, paddingHorizontal: 4 },
  orDivider: { flexDirection: "row", alignItems: "center", gap: 12 },
  requestIdle: { paddingVertical: 12, textAlign: "center" },
  approvalPanel: { gap: 20, paddingBottom: 16 },
  approvalHeading: { flexDirection: "row", alignItems: "center", gap: 12 },
  approvalActions: { flexDirection: "row", gap: 12 },
  flexAction: { flex: 1 },
  advancedSettingsToggle: { alignSelf: "flex-start", marginLeft: -12 },
  relaySettings: { gap: 12 },
  qrContent: { alignItems: "center", gap: 16, paddingBottom: 24 },
  qrFrame: { alignSelf: "center", padding: 12, borderRadius: 12, backgroundColor: "white" },
  qrPlaceholder: { alignItems: "center", justifyContent: "center", gap: 12 },
  snackbar: { marginBottom: 88 },
  scanner: { flex: 1, backgroundColor: "black" },
  scanFooter: { position: "absolute", left: 20, right: 20, bottom: 30, gap: 12 },
  scanText: { color: "white", textAlign: "center" },
  flex: { flex: 1 },
} as const);
