import { Libp2p } from "@ckb-ccc/libp2p";
import { multiaddr } from "@multiformats/multiaddr";
import { zlibSync } from "fflate";
import * as lp from "it-length-prefixed";
import { describe, expect, it } from "vitest";

import {
  MAX_DECOMPRESSED_ADDRESSES_LENGTH,
  PairingEndpointError,
  PairingEndpointRoleError,
  decodePairingEndpointMobile,
  encodePairingEndpointMobile,
} from "./pairingEndpointCodec";

const addresses = [
  multiaddr("/dns4/relay.ckbccc.com/tcp/443/wss/p2p/12D3KooWJ8vVZk6QpxCdu6iBqfQBvNqkgTZJgVn1NwQpPmyTn9zX"),
  multiaddr("/ip4/127.0.0.1/udp/4001/webrtc-direct"),
];

describe("mobile pairing endpoint codec", () => {
  it("is decoded by CCC's browser codec", async () => {
    const endpoint = await encodePairingEndpointMobile(
      "https://app.ckbccc.com/khie#/pair?old=1",
      addresses,
      "mobile-secret",
      "provider",
    );
    const decoded = await Libp2p.decodePairingEndpoint(endpoint, "provider");
    expect(decoded.secret).toBe("mobile-secret");
    expect(decoded.addresses.map(String)).toEqual(addresses.map(String));
  });

  it("decodes endpoints generated by CCC", async () => {
    const endpoint = await Libp2p.encodePairingEndpoint(
      "https://app.ckbccc.com/khie#/pair",
      addresses,
      "browser-secret",
      "connector",
    );
    const decoded = await decodePairingEndpointMobile(endpoint, "connector");
    expect(decoded.secret).toBe("browser-secret");
    expect(decoded.addresses.map(String)).toEqual(addresses.map(String));
  });

  it("rejects role mismatches, malformed compression and too many addresses", async () => {
    const endpoint = await encodePairingEndpointMobile(
      "https://example.com/#/pair",
      addresses,
      "secret",
      "provider",
    );
    await expect(decodePairingEndpointMobile(endpoint, "connector")).rejects.toBeInstanceOf(
      PairingEndpointRoleError,
    );
    await expect(
      decodePairingEndpointMobile("https://example.com/#/pair?role=connector&addresses=nope&secret=x"),
    ).rejects.toBeInstanceOf(PairingEndpointError);
    await expect(
      encodePairingEndpointMobile(
        "https://example.com",
        Array.from({ length: 17 }, () => addresses[1]!),
        "secret",
      ),
    ).rejects.toThrow("at most 16");
  });

  it("enforces the decompressed byte limit", async () => {
    const compressed = base64Url(zlibSync(new Uint8Array(MAX_DECOMPRESSED_ADDRESSES_LENGTH + 1)));
    await expect(
      decodePairingEndpointMobile(
        `https://example.com/#/pair?role=connector&addresses=${compressed}&secret=x`,
        "connector",
      ),
    ).rejects.toBeInstanceOf(PairingEndpointError);
  });

  it("rejects a decoded list containing more than 16 addresses", async () => {
    const encoded = [...lp.encode(Array.from({ length: 17 }, () => addresses[1]!.bytes))];
    const bytes = concat(encoded.map((chunk) => chunk.subarray()));
    const compressed = base64Url(zlibSync(bytes));
    await expect(
      decodePairingEndpointMobile(
        `https://example.com/#/pair?role=connector&addresses=${compressed}&secret=x`,
        "connector",
      ),
    ).rejects.toBeInstanceOf(PairingEndpointError);
  });
});

function concat(chunks: Uint8Array[]): Uint8Array {
  const result = new Uint8Array(chunks.reduce((sum, chunk) => sum + chunk.length, 0));
  let offset = 0;
  for (const chunk of chunks) {
    result.set(chunk, offset);
    offset += chunk.length;
  }
  return result;
}

function base64Url(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("base64url");
}
