const { withAppBuildGradle } = require("expo/config-plugins");

const MARKER = "// @generated by withAndroidAbiSplits";
const ABI_SPLITS = `${MARKER}
    if ((findProperty("khie.enableAbiSplits") ?: "false").toBoolean()) {
        splits {
            abi {
                reset()
                enable true
                universalApk true
                include "arm64-v8a", "armeabi-v7a", "x86", "x86_64"
            }
        }
    }
`;

module.exports = function withAndroidAbiSplits(config) {
  return withAppBuildGradle(config, (buildGradleConfig) => {
    if (buildGradleConfig.modResults.language !== "groovy") {
      throw new Error("withAndroidAbiSplits requires a Groovy app build.gradle");
    }

    if (buildGradleConfig.modResults.contents.includes(MARKER)) {
      return buildGradleConfig;
    }

    const androidBlock = "android {\n";
    if (!buildGradleConfig.modResults.contents.includes(androidBlock)) {
      throw new Error("withAndroidAbiSplits could not find the Android block");
    }

    buildGradleConfig.modResults.contents =
      buildGradleConfig.modResults.contents.replace(
        androidBlock,
        `${androidBlock}    ${ABI_SPLITS}`,
      );

    return buildGradleConfig;
  });
};
