const { withAppBuildGradle } = require("expo/config-plugins");

const MARKER = "// @generated by withReleaseSigning";
const SIGNING_ENVIRONMENT = `
${MARKER}
def khieReleaseStoreFile = System.getenv("KHIE_RELEASE_STORE_FILE")
def khieReleasePassword = System.getenv("KHIE_RELEASE_PASSWORD")
def khieReleaseKeyAlias = "khie-mobile-release"
def khieReleaseSigningConfigured = [
    khieReleaseStoreFile,
    khieReleasePassword,
].every { value -> value != null && !value.trim().isEmpty() }
def khieRequestsReleaseBuild = gradle.startParameter.taskNames.any { task ->
    task.toLowerCase().contains("release")
}
`;

const RELEASE_SIGNING_CONFIG = `
        ${MARKER}
        release {
            if (khieReleaseSigningConfigured) {
                storeFile file(khieReleaseStoreFile)
                storePassword khieReleasePassword
                keyAlias khieReleaseKeyAlias
                keyPassword khieReleasePassword
                storeType "PKCS12"
            }
        }
`;

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (buildGradleConfig) => {
    if (buildGradleConfig.modResults.language !== "groovy") {
      throw new Error("withReleaseSigning requires a Groovy app build.gradle");
    }

    if (buildGradleConfig.modResults.contents.includes(MARKER)) {
      return buildGradleConfig;
    }

    const androidBlock = "android {\n";
    const signingConfigsBlock = "    signingConfigs {\n";
    if (
      !buildGradleConfig.modResults.contents.includes(androidBlock)
      || !buildGradleConfig.modResults.contents.includes(signingConfigsBlock)
    ) {
      throw new Error("withReleaseSigning could not find Android signing configuration");
    }

    let contents = buildGradleConfig.modResults.contents.replace(
      androidBlock,
      `${SIGNING_ENVIRONMENT}\n${androidBlock}`,
    );
    contents = contents.replace(
      /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?)signingConfig signingConfigs\.debug/,
      `$1if (khieRequestsReleaseBuild && !khieReleaseSigningConfigured) {
                throw new GradleException("Release signing credentials are required")
            }
            signingConfig signingConfigs.release`,
    );
    contents = contents.replace(
      signingConfigsBlock,
      `${signingConfigsBlock}${RELEASE_SIGNING_CONFIG}`,
    );

    if (!contents.includes("signingConfig signingConfigs.release")) {
      throw new Error("withReleaseSigning could not configure the release build type");
    }

    buildGradleConfig.modResults.contents = contents;
    return buildGradleConfig;
  });
};
